on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  terraform-validate:
    name: Run terraform validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5
          terraform_wrapper: false
      - run: |
          terraform init
          terraform validate
        working-directory: examples/

  terratest:
    name: Run terratest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.20
      - run: |
          go mod download
          go test -v -timeout 30m ./...
