on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  SecretsManagerValidateSuccess: 
    name: Run terratest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: setup go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: 1.21.6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0
        with:
          terraform_version: "1.5.7"

      - run: |
          go mod download
          go test -v -timeout 30m -run TestSMValidateSuccess ./...
        working-directory: test

  SecretsManagerValidateFailure: 
    name: Run terratest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: setup go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: 1.21.6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: "1.5.7"

      - run: |
          go mod download
          go test -v -timeout 30m -run TestSMValidateFailure ./...
        working-directory: test
        