on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  SecretsManagerValidateSuccess: 
    name: Run terratest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.6
      - run: |
          go mod download
          go test -v -timeout 30m -run TestSMValidateSuccess ./...
        working-directory: test

  SecretsManagerValidateFailure: 
    name: Run terratest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.6
      - run: |
          go mod download
          go test -v -timeout 30m -run TestSMValidateFailure ./...
        working-directory: test
        